language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
services:
  - postgresql
  - mysql
  - redis-server
before_install:
  - openssl aes-256-cbc -K $encrypted_081cd9764c51_key -iv $encrypted_081cd9764c51_iv
    -in github_deploy_key.enc -out github_deploy_key -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
  - "[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest"
  - npm install -g greenkeeper-lockfile@1
  - npm install -g codecov
  - mysql -e 'CREATE DATABASE IF NOT EXISTS site;'
  - mysql -e "CREATE USER 'user'@'localhost' IDENTIFIED BY 'secret';"
  - mysql -e "GRANT ALL ON site.* TO 'user'@'localhost'";
  - mysql site < test/files/bspborg.sql
install: npm install
before_script: greenkeeper-lockfile-update
script: npm test -- --ci --runInBand --collectCoverage || npm test -- --ci --runInBand  --collectCoverage
after_script:
  - greenkeeper-lockfile-upload
  - codecov
deploy:
  provider: heroku
  api_key:
    secure: sPukIrAEy2tI+93AnZl/QzGBVStfTRGFaEApLLvmnCgW2xsNHzvMj7fYeRMFkQasREKXhwG0tEwWeJqH7uPsWE7/Da2DQTLBrd6rEsaNljLWH5BeLEnHYCye+OiEBka+z53eG8ITs1wG/g7C8QGeXXUBsiG8+ZS9jRRRbNAJ/uF5oDLQlX+/VhSuSXjvs5LsvKVhfaIRhKleSFF7hu3iNeUZrG0RpVVbu/kGfyrMv94ikML9SP5LKuerY0Aqe46EJxBbYcmaQsb3pcJfvsSU/pYKAtRSjyHV3fg4R823EbmC3r+P6yFCam3a2mOMUz74jMTMYJimfv44uW6q/6WfBz5m9ktyNGpqb0fmoKv65lEXMU6u47H2AOr9LvBw42Ff+UjTNMGBBqjrWSnL9aZi/FDE+Xnjo/FS1YRc64PH+imj7azs8rMuTRZf1uOPeDHU3E5icGvK0p1ts8z0fTZaQvJlqGQmHWskgixegXnzi9cWSEpSYts64MdBPo4T5amjzpjKOUsaVb7qteYzqFCeWzfgubSmgEmty6XQsAvYncghfzVvBEupU9J+Vq5ZDxypfjpljzGr+ddO7SVUWwlM8m+Awktcn3SrnKjTBpNGIJ8FOXIVw+iO0mQQgfPrDbAmzFEtc/FQ2lMPtwkdb0TD/pg/ceteEsS+EBWtgXjUFwg=
  app: 
    master: bspb-members-staging
  on:
    repo: BspbOrg/members-server
  run:
    - npm run migrate
env:
  global:
    secure: qlFEymOAYt0wuH4KZ7su6RN8V6C1uwEO1tbkCsVbWTpAjWwaPsA1rmeYKQA5Oy9wJ8HHkYCpD8bAY3PoVoyCza2GfQjs3A24/Sm5Gb/bOt2K3ajcrsQnny7U+LYI5phbyuiuOQACQjYfFTh8QAZ4yITQaau/cSknC+y5lFV4wDEh0e/pe0bCEtAh0IYIpwcc2VhsJzUgqD6pvUzynO01xToY5wNa6OhwgPpIJ+vWL3drx0mlWlDTMfLHy4ugwBKsud2VXblht53rrKVgEvjo8LMxCORrCRLBDbAA3V8ZqPrebJhbXI/B2CjASIsptmKX5ESJDWDGCAaBRlyqPlSNxEnccyts6pXEfKIACC/q7+MRHO+wdG2j+zG3irs8t0sAcl6BPZfYy5agHN6bxoUSBr8ECvcQeRLPyJFOzEa56uQT8FSYJFPjxHhQf80XOHU+wvmvCwYMTWPWdj9zZRknbMdEUPSYsVvsBzevpP/Ct0werVqP9rRqqMG7ykL8MUPXVCPEgaqnFxvJo92EJySmt1fn3FaiN4gi0M/27GHwyAliN+eOl6vgsgawo4yn1+7UFPqmtDmDiWkKYRGgCc9ylbMP7CSi3LMuRKVGHmbA4eE+O/yM5n7IZN52crdoxURdr7r/7qC5PrJcup4eP5LCWpSW9PUilmZVe+mEnFnbX6Q=

