api:
  image: node:9
  volumes:
    - .:/usr/src/app
  command: [ "npm", "start" ]
  links:
    - db
    - redis
    - bspborg
  ports:
    - "5000:5000"
  environment:
    PORT: 5000
    DATABASE_URL: 'postgres://user:secret@db:5432/members'
    REDIS_HOST: redis
    REDIS_PORT: 6379
    REDIS_DB: 0
    BSPBORG_DATABASE_URL: 'mysql://user:secret@bspborg/site'

db:
  image: postgres:10
  environment:
    POSTGRES_USER: 'user'
    POSTGRES_PASSWORD: 'secret'
    POSTGRES_DB: 'members'
  ports:
    - "5432:5432"

dbadmin:
  image: adminer
  links:
    - db
  ports:
    - "8080:8080"

redis:
  image: redis
  ports:
    - "6379:6379"

bspborg:
  image: mysql:5.6.39
  command: --default-authentication-plugin=mysql_native_password --character-set-server=cp1251 --collation-server=cp1251_bulgarian_ci
  environment:
    MYSQL_ROOT_PASSWORD: 'secret'
    MYSQL_DATABASE: 'site'
    MYSQL_USER: 'user'
    MYSQL_PASSWORD: 'secret'
  ports:
    - "3306:3306"
  volumes:
    - "./test/files/bspborg.sql:/docker-entrypoint-initdb.d/01-init.sql"
