api:
  image: node:9
  volumes:
    - .:/usr/src/app
  command: [ "npm", "start" ]
  links:
    - db
    - redis
  ports:
    - "5000:5000"
  environment:
    PORT: 5000
    DATABASE_URL: 'postgres://user:secret@db:5432/members'
    REDIS_HOST: redis
    REDIS_PORT: 6379
    REDIS_DB: 0

db:
  image: postgres:10
  environment:
    POSTGRES_USER: 'user'
    POSTGRES_PASSWORD: 'secret'
    POSTGRES_DB: 'members'
  ports:
    - "5432:5432"

dbadmin:
  image: adminer
  links:
    - db
  ports:
    - "8080:8080"

redis:
  image: redis
  ports:
    - "6379:6379"
